// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VoteServiceClient is the client API for VoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoteServiceClient interface {
	ReadCriptoCurrencies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Criptos, error)
	AddCriptoCurrency(ctx context.Context, in *CriptoCurrency, opts ...grpc.CallOption) (*CriptoCurrency, error)
	UpdateCriptoCurrency(ctx context.Context, in *CriptoCurrency, opts ...grpc.CallOption) (*CriptoCurrency, error)
	RemoveCriptoCurrency(ctx context.Context, in *CriptoCurrency, opts ...grpc.CallOption) (*CriptoCurrency, error)
	Upvote(ctx context.Context, in *Vote, opts ...grpc.CallOption) (*Vote, error)
	Downvote(ctx context.Context, in *Vote, opts ...grpc.CallOption) (*Vote, error)
}

type voteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoteServiceClient(cc grpc.ClientConnInterface) VoteServiceClient {
	return &voteServiceClient{cc}
}

func (c *voteServiceClient) ReadCriptoCurrencies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Criptos, error) {
	out := new(Criptos)
	err := c.cc.Invoke(ctx, "/core.VoteService/ReadCriptoCurrencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voteServiceClient) AddCriptoCurrency(ctx context.Context, in *CriptoCurrency, opts ...grpc.CallOption) (*CriptoCurrency, error) {
	out := new(CriptoCurrency)
	err := c.cc.Invoke(ctx, "/core.VoteService/AddCriptoCurrency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voteServiceClient) UpdateCriptoCurrency(ctx context.Context, in *CriptoCurrency, opts ...grpc.CallOption) (*CriptoCurrency, error) {
	out := new(CriptoCurrency)
	err := c.cc.Invoke(ctx, "/core.VoteService/UpdateCriptoCurrency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voteServiceClient) RemoveCriptoCurrency(ctx context.Context, in *CriptoCurrency, opts ...grpc.CallOption) (*CriptoCurrency, error) {
	out := new(CriptoCurrency)
	err := c.cc.Invoke(ctx, "/core.VoteService/RemoveCriptoCurrency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voteServiceClient) Upvote(ctx context.Context, in *Vote, opts ...grpc.CallOption) (*Vote, error) {
	out := new(Vote)
	err := c.cc.Invoke(ctx, "/core.VoteService/Upvote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voteServiceClient) Downvote(ctx context.Context, in *Vote, opts ...grpc.CallOption) (*Vote, error) {
	out := new(Vote)
	err := c.cc.Invoke(ctx, "/core.VoteService/Downvote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoteServiceServer is the server API for VoteService service.
// All implementations must embed UnimplementedVoteServiceServer
// for forward compatibility
type VoteServiceServer interface {
	ReadCriptoCurrencies(context.Context, *emptypb.Empty) (*Criptos, error)
	AddCriptoCurrency(context.Context, *CriptoCurrency) (*CriptoCurrency, error)
	UpdateCriptoCurrency(context.Context, *CriptoCurrency) (*CriptoCurrency, error)
	RemoveCriptoCurrency(context.Context, *CriptoCurrency) (*CriptoCurrency, error)
	Upvote(context.Context, *Vote) (*Vote, error)
	Downvote(context.Context, *Vote) (*Vote, error)
	mustEmbedUnimplementedVoteServiceServer()
}

// UnimplementedVoteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVoteServiceServer struct {
}

func (UnimplementedVoteServiceServer) ReadCriptoCurrencies(context.Context, *emptypb.Empty) (*Criptos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadCriptoCurrencies not implemented")
}
func (UnimplementedVoteServiceServer) AddCriptoCurrency(context.Context, *CriptoCurrency) (*CriptoCurrency, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCriptoCurrency not implemented")
}
func (UnimplementedVoteServiceServer) UpdateCriptoCurrency(context.Context, *CriptoCurrency) (*CriptoCurrency, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCriptoCurrency not implemented")
}
func (UnimplementedVoteServiceServer) RemoveCriptoCurrency(context.Context, *CriptoCurrency) (*CriptoCurrency, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCriptoCurrency not implemented")
}
func (UnimplementedVoteServiceServer) Upvote(context.Context, *Vote) (*Vote, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upvote not implemented")
}
func (UnimplementedVoteServiceServer) Downvote(context.Context, *Vote) (*Vote, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Downvote not implemented")
}
func (UnimplementedVoteServiceServer) mustEmbedUnimplementedVoteServiceServer() {}

// UnsafeVoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoteServiceServer will
// result in compilation errors.
type UnsafeVoteServiceServer interface {
	mustEmbedUnimplementedVoteServiceServer()
}

func RegisterVoteServiceServer(s grpc.ServiceRegistrar, srv VoteServiceServer) {
	s.RegisterService(&VoteService_ServiceDesc, srv)
}

func _VoteService_ReadCriptoCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServiceServer).ReadCriptoCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.VoteService/ReadCriptoCurrencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServiceServer).ReadCriptoCurrencies(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoteService_AddCriptoCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CriptoCurrency)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServiceServer).AddCriptoCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.VoteService/AddCriptoCurrency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServiceServer).AddCriptoCurrency(ctx, req.(*CriptoCurrency))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoteService_UpdateCriptoCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CriptoCurrency)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServiceServer).UpdateCriptoCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.VoteService/UpdateCriptoCurrency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServiceServer).UpdateCriptoCurrency(ctx, req.(*CriptoCurrency))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoteService_RemoveCriptoCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CriptoCurrency)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServiceServer).RemoveCriptoCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.VoteService/RemoveCriptoCurrency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServiceServer).RemoveCriptoCurrency(ctx, req.(*CriptoCurrency))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoteService_Upvote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServiceServer).Upvote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.VoteService/Upvote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServiceServer).Upvote(ctx, req.(*Vote))
	}
	return interceptor(ctx, in, info, handler)
}

func _VoteService_Downvote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServiceServer).Downvote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.VoteService/Downvote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServiceServer).Downvote(ctx, req.(*Vote))
	}
	return interceptor(ctx, in, info, handler)
}

// VoteService_ServiceDesc is the grpc.ServiceDesc for VoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.VoteService",
	HandlerType: (*VoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadCriptoCurrencies",
			Handler:    _VoteService_ReadCriptoCurrencies_Handler,
		},
		{
			MethodName: "AddCriptoCurrency",
			Handler:    _VoteService_AddCriptoCurrency_Handler,
		},
		{
			MethodName: "UpdateCriptoCurrency",
			Handler:    _VoteService_UpdateCriptoCurrency_Handler,
		},
		{
			MethodName: "RemoveCriptoCurrency",
			Handler:    _VoteService_RemoveCriptoCurrency_Handler,
		},
		{
			MethodName: "Upvote",
			Handler:    _VoteService_Upvote_Handler,
		},
		{
			MethodName: "Downvote",
			Handler:    _VoteService_Downvote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model/vote.proto",
}
